export const STYLE_PROPERTY_DEFINITIONS = [
  { key: "fillColor", type: "color", geometryTypes: ["polygon"] },
  { key: "fillOpacity", type: "number", geometryTypes: ["polygon"], min: 0, max: 1 },
  { key: "fillAntialias", type: "boolean", geometryTypes: ["polygon"] },
  { key: "strokeColor", type: "color", geometryTypes: ["polygon", "line"] },
  { key: "strokeOpacity", type: "number", geometryTypes: ["polygon", "line"], min: 0, max: 1 },
  { key: "strokeWidth", type: "number", geometryTypes: ["polygon", "line"], min: 0, max: 24 },
  { key: "strokeBlur", type: "number", geometryTypes: ["polygon", "line"], min: 0, max: 24 },
  { key: "strokeDasharray", type: "dasharray", geometryTypes: ["polygon", "line"] },
  { key: "strokeOffset", type: "number", geometryTypes: ["polygon", "line"], min: -24, max: 24 },
  { key: "lineCap", type: "enum", geometryTypes: ["polygon", "line"], options: ["butt", "round", "square"] },
  { key: "lineJoin", type: "enum", geometryTypes: ["polygon", "line"], options: ["bevel", "round", "miter"] },
  { key: "circleColor", type: "color", geometryTypes: ["point"] },
  { key: "circleOpacity", type: "number", geometryTypes: ["point"], min: 0, max: 1 },
  { key: "circleRadius", type: "number", geometryTypes: ["point"], min: 0, max: 50 },
  { key: "circleBlur", type: "number", geometryTypes: ["point"], min: -1, max: 1 },
  { key: "circleStrokeColor", type: "color", geometryTypes: ["point"] },
  { key: "circleStrokeOpacity", type: "number", geometryTypes: ["point"], min: 0, max: 1 },
  { key: "circleStrokeWidth", type: "number", geometryTypes: ["point"], min: 0, max: 24 },
  { key: "opacity", type: "number", geometryTypes: ["raster"], min: 0, max: 1 },
  { key: "rasterOpacity", type: "number", geometryTypes: ["raster"], min: 0, max: 1 },
  { key: "brightnessMin", type: "number", geometryTypes: ["raster"], min: 0, max: 1 },
  { key: "brightnessMax", type: "number", geometryTypes: ["raster"], min: 0, max: 1 },
  { key: "contrast", type: "number", geometryTypes: ["raster"], min: -1, max: 1 },
  { key: "saturation", type: "number", geometryTypes: ["raster"], min: -1, max: 1 },
  { key: "hueRotate", type: "number", geometryTypes: ["raster"], min: -360, max: 360 },
  { key: "fadeDuration", type: "number", geometryTypes: ["raster"], min: 0, max: 60000 },
  { key: "resampling", type: "enum", geometryTypes: ["raster"], options: ["linear", "nearest"] },
  { key: "visible_by_default", type: "boolean", geometryTypes: ["point", "line", "polygon", "raster"] },
];
